name: "Mathlight"

on:
  push:
    tags:
      - 'v*'

jobs:
  build-n-publish:
    runs-on: ubuntu-latest
    # Cette section permet à GitHub de s'authentifier de manière moderne auprès de PyPI
    permissions:
      id-token: write  
      contents: read

    steps:
      - uses: actions/checkout@v4 # Version mise à jour pour 2026
      - name: Set up Python
        uses: actions/setup-python@v5 # Version mise à jour pour 2026
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: pip install build twine

      - name: Build package
        run: python -m build

      - name: Publish to PyPI
        # Utilise l'action officielle de PyPI pour plus de sécurité
        uses: pypa/gh-action-pypi-publish@release/v1
